#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DongsungLibraryMobile.Resource", IsApplication=true)]

namespace DongsungLibraryMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_logagain = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ico = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ico_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int startup_image = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int btnChangePW = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btnCheckBook = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int button1 = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int imagenotileft = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout1 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout2 = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int text = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int textView2 = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int txtID = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int txtPW = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int viewList = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CheckList = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int customnotification = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ico = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int 대출기록조회 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int 로그인 = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int 로그인정보변경 = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int 여기에목록이표시됩니다 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int 여기에목록이표시됩니다2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Gloveman = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int startup = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
